spring:
  profiles:
    active: test
---
server:
  port: 8201
spring:
  profiles: dev     #开发环境
  application:
    name: microservicecloud-config-wp-dev

eureka:
  client:           #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka-dev.com:7001/eureka/
---
server:
  port: 8201
spring:
  profiles: test   #测试环境
  application:
    name: microservicecloud-config-wp-test

eureka:
  client:           #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka-dev.com:7001/eureka/

